move PWD to  before executing slice scripts.

diff --git a/experimentbase/smp/init/verify b/experimentbase/smp/init/verify
--- a/experimentbase/smp/init/verify
+++ b/experimentbase/smp/init/verify
@@ -4,6 +4,9 @@ if [ -f etc/slice-functions ] ; then
     source etc/slice-functions
 elif [ -f /etc/slice-functions ] ; then
     source /etc/slice-functions
+else
+    echo "Error: /etc/slice-functions is missing"
+    exit 1
 fi
 
 command=$1
